version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  backend:
    image: izmodizm/kittygram_backend:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    depends_on:
      - db

  frontend:
    image: izmodizm/kittygram_frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  gateway:
    image: izmodizm/kittygram_gateway:latest
    ports:
      - "9000:80"
    depends_on:
      - frontend
